version: '3.8'
services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: professional_portfolio_container
    ports:
      - "8080:80" # Can see 8080 port in Web browser  
    
    # Performance: Resource management (CPU/Memory limits)
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    
    # Reliability: To check if the Container works propearly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Networking: Custom bridge network for isolation
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge